name: Deploy Laravel App to EC2

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sync Files to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
          DESTINATION_PATH: ${{ secrets.AWS_PATH }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem
          rsync -avz -e "ssh -i /tmp/private_key.pem" --exclude=".git" --exclude="vendor" --exclude="node_modules" ./ ${SSH_USER}@${SSH_HOST}:${DESTINATION_PATH}

      - name: SSH into EC2 and Set Permissions
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
          DESTINATION_PATH: ${{ secrets.AWS_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key.pem ${SSH_USER}@${SSH_HOST} << 'EOF'
            cd ${DESTINATION_PATH}
            sudo git pull origin master
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo chown -R www-data:www-data ${DESTINATION_PATH}
            sudo systemctl restart apache2  # Restart web server
          EOF
